version: "3.9"

services:
  web:
    build: ./web
    container_name: politicia_web
    expose:
      - "8080"
    restart: always

  nginx:
    image: nginx:latest
    container_name: politicia_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot_politicia
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    entrypoint: "/bin/sh"
    restart: always
