###############################
# REDIRECIONA HTTP -> HTTPS
###############################
server {
    listen 80;
    server_name politicia.biz;

    return 301 https://$host$request_uri;
}

###############################
# SERVIDOR HTTPS COM SSL
###############################
server {
    listen 443 ssl;
    server_name politicia.biz;

    ssl_certificate     /etc/letsencrypt/live/politicia.biz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/politicia.biz/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    ###############################
    # PARA RENOVAÇÃO DO CERTBOT
    ###############################
    location /.well-known/acme-challenge/ {
        alias /var/www/html/.well-known/acme-challenge/;
    }

    ###############################
    # SERVIR STATIC DO FLASK!
    ###############################
    location /static/ {
        alias /app/static/;
    }

    ###############################
    # PROXY PARA O FLASK
    ###############################
    location / {
        proxy_pass http://web:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
